esphome:
  name: vfd4
  friendly_name: "VFD4 Clock"
  platformio_options:
    board_build.f_cpu: 26000000L

esp8266:
  board: esp12e

logger:
  level: DEBUG

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  fast_connect: true

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_enckey

ota:
  - platform: esphome
    password: !secret esphome_ota

packages:
  remote_package:
    url: https://github.com/trunneml/esphome-vfd4-clock
    ref: main
    refresh: 300s
    files:
      - packages/vfd4clock.yaml # Basic package

display:
  - id: !extend vfd4display
    lambda: |-
      it.strftime("%H:%M", id(ds1302_time).now());

binary_sensor:
  - id: !extend setbtn
    on_press:
      then:
        - switch.toggle: displblank

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Berlin
    # instead try to synchronize via network repeatedly ...
    on_time_sync:
      then:
        # ... and update the RTC when the synchronization was successful
        ds1302.write_time:
