---
name: CI

on:
  push:


env:
  DEFAULT_PYTHON: "3.9"

jobs:
  esphome:
    name: Test component and package
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Check out code from GitHub
        uses: actions/checkout@v4.1.7
      - name: Compile vfd4clock_example.yaml
        run: |
          pip install esphome
          cat <<EOT >>secrets.yaml
          wifi_ssid: examplewifissid
          wifi_password: examplewifipassword
          esphome_ota: example
          EOT
          esphome compile vfd4clock_example.yaml